#!/usr/bin/env python3

from sync_with_galaxy.galaxysync import GalaxySync

import argparse
import sys

if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  requiredNamed = parser.add_argument_group('required named arguments')
  requiredNamed.add_argument("-address", required=True, help="address of the local Galaxy instance")
  requiredNamed.add_argument("-api_key", required=True, help="a Galaxy admin API key")
  requiredNamed.add_argument("-path", required=True, help="the path to search for files to add")
  parser.add_argument("-debug", action='store_true', help="toggles DEBUG-level logging output")
  
  try:
    args = parser.parse_args()
  except SystemExit as err:
    if err.code == 2:
      print("\n")
      parser.print_help()
    sys.exit()  
  gs = GalaxySync(args.address, args.api_key, "/tmp/mihc_temp", 
    loglevel="DEBUG" if args.debug else None)